# Generated by Django 4.0.5 on 2022-07-26 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('demo_link', models.TextField(blank=True, max_length=2000, null=True)),
                ('source_link', models.TextField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.UUID('ebdf00e8-9b3b-4e94-aeeb-3398fb4af93f'), editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
